### PR TITLE
Make compiled container (almost) idempotent

### LINKED ISSUE #604: Make CompiledContainer idempotent?
Heroku [offers free "dyno's" / containers, which go to "sleep" after idling 30 minutes](https://devcenter.heroku.com/articles/free-dyno-hours), in the logs this looks like this:

```
2018-06-08T13:36:14.928015+00:00 heroku[web.1]: Idling
2018-06-08T13:36:14.928583+00:00 heroku[web.1]: State changed from up to down
2018-06-08T13:36:15.659288+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-06-08T13:36:15.772020+00:00 heroku[web.1]: Process exited with status 143
2018-06-08T13:36:15.671374+00:00 app[web.1]: Going down, terminating child processes...
2018-06-11T06:38:43.485395+00:00 heroku[web.1]: Unidling
2018-06-11T06:38:43.485781+00:00 heroku[web.1]: State changed from down to starting
2018-06-11T06:38:52.247525+00:00 heroku[web.1]: Starting process with command `vendor/bin/heroku-php-apache2 public/`
2018-06-11T06:38:56.892979+00:00 app[web.1]: DOCUMENT_ROOT changed to 'public/'
2018-06-11T06:38:56.910706+00:00 app[web.1]: Using WEB_CONCURRENCY=2 processes.
2018-06-11T06:38:56.918291+00:00 app[web.1]: Starting php-fpm...
2018-06-11T06:38:58.919763+00:00 app[web.1]: Starting httpd...
2018-06-11T06:38:59.300606+00:00 heroku[web.1]: State changed from starting to up
```

After waking up, a problem seems to occurs with the combination of:

- PHP-DI CompiledContainer
- [OPCache file cache](http://php.net/manual/en/book.opcache.php)
  - Note that [OPCache file cache](http://php.net/manual/en/opcache.configuration.php#ini.opcache.file-cache) is enabled: OPCache entries are also saved to disk, so upon server start they are available immediately. Not sure what parts of this Heroku "keeps" between idling / unindling...

```
Array
(
    [type] => 1
    [message] => Uncaught Error: Call to undefined method CompiledContainer::get5b1e190a4fff9261052747() in /app/vendor/php-di/php-di/src/CompiledContainer.php:53
Stack trace:
#0 /app/data/cache/CompiledContainer.php(39133): DI\CompiledContainer->get('settings.amazon...')
#1 /app/data/cache/CompiledContainer.php(39143): CompiledContainer->get5b1e190b4c240336720486()
#2 /app/vendor/php-di/php-di/src/CompiledContainer.php(53): CompiledContainer->get5b1e190b4c17c596082894()
#3 /app/data/cache/CompiledContainer.php(39098): DI\CompiledContainer->get('Aws\\Credentials...')
#4 [internal function]: CompiledContainer::{closure}(Object(CompiledContainer))
#5 /app/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#6 /app/vendor/php-di/php-di/src/CompiledContainer.php(116): Invoker\Invoker->call(Object(Closure), Array)
#7 /app/data/cache/CompiledContainer.php(39099): DI\CompiledContainer->resolveFactory(Object(Closure), 'awsClientOption...')
#8 /app/vendor/php-di/php-di/src/CompiledContainer.php(53):
    [file] => /app/vendor/php-di/php-di/src/CompiledContainer.php
    [line] => 53
)
```

I am not sure, but I got the feeling that this has to do with the CompiledContainer that is regenerated when the dyno comes back to live, but the OPCode cache is not cleared and still refers to the "old" version of the CompiledContainer. 

This can probably be circumvented when the CompiledContainer is made [idempotent](https://en.wikipedia.org/wiki/Idempotence): "a specific PHP-DI configuration X always results in CompiledContainer Y". Currently some random strings are used in the CompiledContainer which causes each regeneration/compilation of the container to have a different result, while no change in the configuration is made. For example:

- [when determining the methodName](https://github.com/PHP-DI/PHP-DI/blob/cdcf21d2a8a60605e81ec269342d48b544d0dfc7/src/Compiler/Compiler.php#L152)
- [when determining the subEntryName](https://github.com/PHP-DI/PHP-DI/blob/cdcf21d2a8a60605e81ec269342d48b544d0dfc7/src/Compiler/Compiler.php#L264)

Would it be an idea to use a hash to determine these strings so that the result would be the same over and over again? Maybe the content of the Definition should also be taken into account so that "changes" to it result in different names...

### PR DESCRIPTION
**Pull request by diesse**
Using a progressive counter for mapped methods/sub entries, container recompilation produces always the same result if definitions do not change.
It's not fully idempotent because changing definitions order leads to a different container, even if functionally unchanged.
Partially fixes #604

### CODE REVIEW

**Comment by holtkamp** [comment]
Nice idea 😸

File: src/Compiler/Compiler.php [hunk 1]
```diff
@@ -48,6 +48,16 @@ class Compiler
      */
     private $entriesToCompile;
 
+    /**
+     * @var int
```
Comment (mnapoli) [inline src/Compiler/Compiler.php]: Could you add a description to this field to explain how/why it's different from the other one?

File: src/Compiler/Compiler.php [hunk 2]
```diff
@@ -48,6 +48,16 @@ class Compiler
...
+     */
+    private $subEntryCounter;
+
+    /**
+     * @var int
+     */
+    private $methodMappingCounter;
```
Comment (mnapoli) [inline src/Compiler/Compiler.php]: Could you add a description to this field to explain how/why it's different from the other one?

File: src/Compiler/Compiler.php [hunk 3]
```diff
@@ -165,7 +175,7 @@ public function compile(
     private function compileDefinition(string $entryName, Definition $definition) : string
     {
         // Generate a unique method name
-        $methodName = str_replace('.', '', uniqid('get', true));
+        $methodName = 'get' . sprintf('%022d', ++$this->methodMappingCounter);
```
Comment (mnapoli) [inline src/Compiler/Compiler.php]: Why is it `%022d` here and `%013d` in the other place? I'm not familiar with this syntax, why use this instead of a concatenation?

File: src/Compiler/Compiler.php (hunk 2 above)
Comment (diesse) [reply src/Compiler/Compiler.php]: I added a description for the fields

File: src/Compiler/Compiler.php (hunk 3 above)
Comment (diesse) [reply src/Compiler/Compiler.php]: It's useless, indeed :blush:
The syntax adds 0-padding to the left of the counter in order to keep the same string length of the original naming scheme.

**Comment by mnapoli** [comment]
Thanks @diesse!

Let's give this a go in a new release!
